### ISSUE TITLE
stable/zed image?

### ISSUE THREAD

**Issue by lukasmrtvy** [osism/openstack-octavia-amphora-image#37]
Any chance to produce also stable/zed image? Thanks

**Comment by berendt** [comment]
We are still preparing Zed. But I can already add this.

**Comment by berendt** [comment]
https://minio.services.osism.tech/openstack-octavia-amphora-image/octavia-amphora-haproxy-zed.qcow2

Please check. Also changed the base image from Focal to Jammy.
